name = "VlessCF"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "c9cd2212-5ae8-46a8-885c-5dccaf4c975e"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
